from redis.exceptions import ConnectionError as ConnectionError, TimeoutError as TimeoutError

class Retry:
    def __init__(self, backoff, retries, supported_errors=...) -> None: ...
    def update_supported_errors(self, specified_errors: list): ...
    def call_with_retry(self, do, fail): ...
